### ISSUE TITLE
please provide a template example

### ISSUE THREAD

**Issue by funkenstrahlen** [lcortess/simple-parse-smtp-adapter#13]
Can you please add a simple mail template example to the project? I do not really know how to create a template based on what is explained in the readme.

**Comment by lcortess** [comment]
So you need a folder by email you want, for example:
```
views/
└── email
    └── reset-password
        ├── html.jade
        └── style.less
```

The `html.jade` is a normal jade template (now called [pug](https://pugjs.org/api/getting-started.html) )
```jade
doctype html
html
  head
    meta(name='viewport', content='width=device-width')
    meta(http-equiv='Content-Type', content='text/html; charset=UTF-8')
    title My Email
  body(bgcolor='#f6f6f6')
    // body
    table.body-wrap(bgcolor='#f6f6f6')
      tr
        td
        td.container(bgcolor='#FFFFFF')
          // content
          div.content
            table
              tr
                td(align="center")
                  h3 Reset Password
              tr
                td(align="center")
                  p You are receiving this email because your address was entered in the forgotten password form when signing in my awesome page.
                  p To recover your account and reset your password, please &nbsp;
                    a(href="#{link}") click here.
                  p If you believe you have received this email in error, please ignore it.

          // /content
        td
    // /body
    // footer
    table.footer-wrap
      tr
        td
        td.container
          // content
          .content
            table
              tr
                td(align='center')
                  p My awesome company
          // /content
        td
    // /footer
```

on `style.less` you have to set a normal [less](http://lesscss.org/) file

```less
h1,
  h2,
  h3 {
    color: #111111;
    font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    font-weight: 200;
    line-height: 1.2em;
    margin: 40px 0 10px;
  }

  h1 {
    font-size: 36px;
  }
  h2 {
    font-size: 28px;
  }
  h3 {
    font-size: 22px;
  }

  p,
  ul,
  ol {
    font-size: 14px;
    font-weight: normal;
    margin-bottom: 10px;
  }

  ul li,
  ol li {
    margin-left: 5px;
    list-style-position: inside;
  }
```
